# Generated by Django 5.1 on 2026-01-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('courses', '0002_lessonattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='allowed_groups',
            field=models.ManyToManyField(blank=True, help_text='Groups that can access this course', to='auth.group'),
        ),
    ]
