# Generated by Django 5.1 on 2026-02-05 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_lessonview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttemptAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen_answer', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1, null=True)),
                ('is_correct', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='lessonattempt',
            name='retake_round',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddIndex(
            model_name='lessonattempt',
            index=models.Index(fields=['user', 'lesson', 'retake_round', 'created_at'], name='courses_les_user_id_8fb342_idx'),
        ),
        migrations.AddField(
            model_name='attemptanswer',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='courses.lessonattempt'),
        ),
        migrations.AddField(
            model_name='attemptanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_answers', to='courses.question'),
        ),
        migrations.AddConstraint(
            model_name='attemptanswer',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='uniq_attempt_question_answer'),
        ),
    ]
