# Generated by Django 5.1 on 2026-02-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_attemptanswer_lessonattempt_retake_round_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_final',
            field=models.BooleanField(default=False, help_text='Mark this lesson as the final course test material'),
        ),
    ]
