# Generated by Django 5.1 on 2026-03-04 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_course_allowed_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBaseModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['section__order', 'order', 'title', 'id'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeBaseSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'title', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='knowledgebasepage',
            options={'ordering': ['module__section__order', 'module__order', 'order', 'title', 'id']},
        ),
        migrations.AddField(
            model_name='knowledgebasepage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='knowledgebasepage',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='courses.knowledgebasemodule'),
        ),
        migrations.AddField(
            model_name='knowledgebasemodule',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.knowledgebasesection'),
        ),
        migrations.AddConstraint(
            model_name='knowledgebasemodule',
            constraint=models.UniqueConstraint(fields=('section', 'slug'), name='uniq_kb_module_section_slug'),
        ),
    ]
