# Generated by Django 5.1 on 2026-03-09 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_remove_kb_module_and_rename_course_labels'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='knowledgebasesection',
            options={'ordering': ['order', 'title', 'id'], 'verbose_name': 'Раздел', 'verbose_name_plural': 'Разделы'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AddField(
            model_name='knowledgebasesection',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='knowledge_base_sections', to='courses.course'),
        ),
    ]
