# Generated by Django 5.1 on 2026-03-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_alter_knowledgebasesection_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupprofile',
            name='allowed_kb_courses',
            field=models.ManyToManyField(blank=True, related_name='allowed_group_profiles_for_kb', to='courses.course'),
        ),
        migrations.AddField(
            model_name='groupprofile',
            name='allowed_kb_sections',
            field=models.ManyToManyField(blank=True, related_name='allowed_group_profiles', to='courses.knowledgebasesection'),
        ),
    ]
