# Generated by Django 5.1 on 2026-03-09 15:47

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_groupprofile_allowed_kb_courses_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='lesson',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.search.CombinedSearchVector(django.contrib.postgres.search.SearchVector('title', config='russian', weight='A'), '||', django.contrib.postgres.search.SearchVector('content', config='russian', weight='B'), django.contrib.postgres.search.SearchConfig('russian')), name='lesson_search_gin'),
        ),
    ]
