# Generated by Django 5.1 on 2026-03-09 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('courses', '0016_lesson_lesson_search_gin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('allowed_groups', models.ManyToManyField(blank=True, related_name='allowed_learning_courses', to='auth.group')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_learning_courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='LearningCourseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.PositiveIntegerField(default=0)),
                ('item_type', models.CharField(choices=[('article', 'Статья'), ('module', 'Модуль'), ('test', 'Тест')], max_length=16)),
                ('is_final_test', models.BooleanField(default=False)),
                ('learning_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='courses.learningcourse')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learning_course_items', to='courses.lesson')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learning_course_items', to='courses.course')),
            ],
            options={
                'verbose_name': 'Элемент курса',
                'verbose_name_plural': 'Элементы курса',
                'ordering': ['order_index', 'id'],
            },
        ),
    ]
