# Generated by Django 5.1 on 2026-03-19 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_learningcourse_learningcourseitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.knowledgebasesection'),
        ),
        migrations.AddField(
            model_name='groupprofile',
            name='allowed_kb_lessons',
            field=models.ManyToManyField(blank=True, related_name='allowed_group_profiles_for_kb', to='courses.lesson'),
        ),
    ]
