# Generated by Django 5.1 on 2026-03-19 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_populate_course_sections'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupprofile',
            name='allowed_kb_pages',
        ),
        migrations.RemoveField(
            model_name='knowledgebasesection',
            name='courses',
        ),
        migrations.DeleteModel(
            name='KnowledgeBasePage',
        ),
    ]
