# Generated by Django 5.1 on 2026-03-23 12:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('courses', '0020_remove_groupprofile_allowed_kb_pages_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='groupprofile',
            name='payment_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='groupprofile',
            name='payment_currency',
            field=models.CharField(default='933', max_length=3),
        ),
        migrations.AddField(
            model_name='groupprofile',
            name='payment_description',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='groupprofile',
            name='payment_language',
            field=models.CharField(default='ru', max_length=8),
        ),
        migrations.AddField(
            model_name='groupprofile',
            name='payment_password',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='groupprofile',
            name='payment_return_url',
            field=models.CharField(default='/payments/return/', max_length=500),
        ),
        migrations.AddField(
            model_name='groupprofile',
            name='payment_user_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='allowed_groups',
            field=models.ManyToManyField(blank=True, help_text='Группы, которым доступен этот модуль.', related_name='allowed_courses', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='is_final',
            field=models.BooleanField(default=False, help_text='Отметьте, если это финальная статья.'),
        ),
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.PositiveIntegerField()),
                ('currency', models.CharField(default='933', max_length=3)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачен'), ('error', 'Ошибка регистрации')], default='pending', max_length=16)),
                ('register_url', models.URLField(max_length=500)),
                ('return_url', models.URLField(max_length=500)),
                ('gateway_order_id', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('gateway_form_url', models.URLField(blank=True, default='', max_length=1000)),
                ('request_payload', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('tariff_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_orders', to='auth.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Платежный заказ',
                'verbose_name_plural': 'Платежные заказы',
                'ordering': ['-created_at'],
            },
        ),
    ]
