# Generated by Django 5.1 on 2026-03-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_groupprofile_payment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentorder',
            name='order_number',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
