# Generated by Django 5.1 on 2026-03-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_fill_paymentorder_order_numbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupprofile',
            name='is_admin_group',
            field=models.BooleanField(default=False),
        ),
    ]
