# Generated by Django 5.1 on 2026-03-25 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_mark_admin_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningcourseitem',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learning_course_items', to='courses.knowledgebasesection'),
        ),
        migrations.AlterField(
            model_name='learningcourseitem',
            name='item_type',
            field=models.CharField(choices=[('article', 'Статья'), ('section', 'Раздел'), ('module', 'Модуль'), ('test', 'Тест')], max_length=16),
        ),
    ]
