# Generated by Django 5.1 on 2026-03-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_learningcourseitem_section_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Тест', 'verbose_name_plural': 'Тесты'},
        ),
        migrations.AlterField(
            model_name='learningcourseitem',
            name='item_type',
            field=models.CharField(choices=[('section', 'Раздел'), ('module', 'Модуль'), ('article', 'Статья'), ('test', 'Тест')], max_length=16),
        ),
    ]
