# Generated by Django 5.1 on 2026-03-27 11:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_alter_question_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningCourseFinalAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retake_round', models.PositiveSmallIntegerField(default=1)),
                ('score', models.PositiveSmallIntegerField(default=0)),
                ('correct', models.PositiveSmallIntegerField(default=0)),
                ('total', models.PositiveSmallIntegerField(default=0)),
                ('passed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('learning_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_attempts', to='courses.learningcourse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_course_final_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningCourseFinalQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=300)),
                ('option_a', models.CharField(max_length=100)),
                ('option_b', models.CharField(max_length=100)),
                ('option_c', models.CharField(max_length=100)),
                ('option_d', models.CharField(blank=True, default='', max_length=100)),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('learning_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_questions', to='courses.learningcourse')),
            ],
            options={
                'verbose_name': 'Вопрос итогового теста',
                'verbose_name_plural': 'Вопросы итогового теста',
            },
        ),
        migrations.CreateModel(
            name='LearningCourseFinalAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen_answer', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='courses.learningcoursefinalattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_answers', to='courses.learningcoursefinalquestion')),
            ],
        ),
        migrations.AddIndex(
            model_name='learningcoursefinalattempt',
            index=models.Index(fields=['user', 'learning_course', 'retake_round', 'created_at'], name='courses_lea_user_id_2ec7ec_idx'),
        ),
        migrations.AddConstraint(
            model_name='learningcoursefinalanswer',
            constraint=models.UniqueConstraint(fields=('attempt', 'question'), name='uniq_learning_course_final_answer'),
        ),
    ]
