# Generated by Django 5.1 on 2026-04-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_learningcoursefinalattempt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attemptanswer',
            name='chosen_answer',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='learningcoursefinalanswer',
            name='chosen_answer',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='learningcoursefinalquestion',
            name='correct_answer',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(max_length=7),
        ),
    ]
