# Generated by Django 5.1 on 2026-04-24 07:47

from django.db import migrations, models


def enable_kb_menu_for_existing_kb_groups(apps, schema_editor):
    GroupProfile = apps.get_model('courses', 'GroupProfile')
    for profile in GroupProfile.objects.all():
        has_kb_access = (
            profile.allowed_kb_lessons.exists()
            or profile.allowed_kb_courses.exists()
            or profile.allowed_kb_sections.exists()
        )
        if has_kb_access:
            profile.show_kb_menu = True
            profile.save(update_fields=['show_kb_menu'])


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0029_alter_attemptanswer_chosen_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupprofile',
            name='show_kb_menu',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(enable_kb_menu_for_existing_kb_groups, migrations.RunPython.noop),
    ]
