# Generated by Django 5.1 on 2026-04-27 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0030_groupprofile_show_kb_menu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['order', 'title', 'id'], 'verbose_name': 'Модуль', 'verbose_name_plural': 'Модули'},
        ),
        migrations.AddField(
            model_name='course',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
