# Generated by Django 5.1 on 2026-04-28 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0031_alter_course_options_course_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseRelearnState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_round', models.PositiveSmallIntegerField(default=1)),
                ('unlocked_through_position', models.PositiveIntegerField(default=0)),
                ('reread_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relearn_states', to='courses.course')),
                ('failed_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relearn_states', to='courses.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_relearn_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'course'), name='uniq_user_course_relearn_state')],
            },
        ),
    ]
