# Generated by Django 5.1 on 2026-04-28 12:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0032_courserelearnstate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningCourseRelearnState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_round', models.PositiveSmallIntegerField(default=1)),
                ('unlocked_article_count', models.PositiveIntegerField(default=0)),
                ('reread_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('failed_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_course_relearn_states', to='courses.lesson')),
                ('learning_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relearn_states', to='courses.learningcourse')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_course_relearn_states', to='courses.course')),
                ('source_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relearn_states', to='courses.learningcourseitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_course_relearn_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'learning_course', 'source_item'), name='uniq_user_learning_course_relearn_state')],
            },
        ),
    ]
